using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ControlBienes.Entities.Patrimonio.MotivoTramite
{
	public enum EnumMotivoTramite : long
	{
		AltaDeBienesEnCompensacion = 1,
		AltaDeMobiliarioPorCargaDesdeElSistemaDeEgresos = 2,
		AltaPorAdjudicacionPorEmbargo = 3,
		AltaPorAdquisicionDeMueblesAniosAnteriores = 4,
		AltaPorAdquisicionDirectaDeBienesMuebles = 5,
		AltaPorAdquisicionDirectaDeBienesMueblesConRecursosFederales = 6,
		AltaPorDiferenciaDeInventarios = 7,
		AltaPorDiferenciaEntregaRecepcion = 8,
		AltaPorDonacionDeBienesMuebles = 9,
		AltaPorExtincion = 10,
		AltaPorLicitacion = 11,
		BajaDeMobiliarioPorExtravio = 12,
		BajaDeMobiliarioPorRobo = 13,
		BajaDeMobiliarioPorSiniestro = 14,
		BajaDeMobiliarioPorInservible = 15,
		BajaDeMobiliarioTotal = 16,
		BajaDeMobiliarioPorDonacion = 17,
		BajaDeMobiliarioPorDuplicidad = 18,
		BajaDeMobiliarioEnArrendamiento = 19,
		BajaDeMobiliarioPorTerminoDeContrato = 20,
		ModificacionDeDatosDeFactura = 21,
		ModificacionDeDatosDeMobiliarioYEquipo = 22,
		ActualizacionDeDatosDeBienesMueblesIncorporadosDelSistemaDeCompras = 23,
		CambioDeCentroDeCostos = 24,
		CambioDeResguardosDeMobiliarioYEquipo = 25,
		TransferenciaDeBienesMuebles = 26,
		DesincorporacionDeBienesMuebles = 27,
		Destruccion = 28,
		Enajenacion = 29,
		AltaPorLicitacionEnOficialiaDeMaquinariasYVehiculos = 30,
		AltaPorLicitacionEnLasDependenciasDeMaquinariaYVehiculos = 31,
		AltaPorDonacionDeMaquinariaYVehiculos = 32,
		AltaPorAdquisicionDirectaDeMaquinariaYVehiculos = 33,
		AltaPorAdquisicionDirectaDeMaquinariaYVehiculosConRecursosFederales = 34,
		AltaPorAdquisicionDeVehiculosAniosAnteriores = 35,
		AltaPorAdjudicacionPorEmbargoDeMaquinariaYVehiculos = 36,
		AltaDeVehiculosPorExtincion = 37,
		AltaDeVehiculosEnCompensacion = 38,
		BajaDeVehiculosPorRobo = 39,
		BajaDeVehiculosPorSiniestro = 40,
		BajaDeVehiculosPorExtravio = 41,
		BajaDeVehiculosPorDuplicidad = 42,
		BajaDeVehiculosPorInservible = 43,
		BajaDeVehiculosTotal = 44,
		BajaDeVehiculosPorDonacion = 45,
		BajaDeVehiculosPorMotivosExtraordinarios = 46,
		ActualizacionDeDatosDeBienesVehiculos = 47,
		ActualizacionDeDatosDeLaFacturaDeBienesVehiculos = 48,
		ActualizacionDeBienesVehiculosIncorporadosDelSistemaDeCompras = 49,
		CambioDeCentroDeCostosVehiculos = 50,
		TransferenciasVehiculos = 51,
		CambioDeResguardante = 52,
		Desincorporacion = 53,
		EnajenacionVehiculos = 54,
		DestruccionVehiculos = 55,
		AltaPorInscripcionPrimitiva = 56,
		AltaPorDonacion = 57,
		AltaPorCompraventa = 58,
		AltaPorDivision = 59,
		AltaPorPermuta = 60,
		AltaPorAdjudicacionATituloGratuito = 61,
		AltaPorCompraventaJudicial = 62,
		AltaPorExpropiacion = 63,
		BajaPorCompraventa = 64,
		BajaPorDonacion = 65,
		BajaPorUnion = 66,
		BajaPorPermuta = 67,
		BajaPorDacionEnPago = 68,
		BajaPorSentenciaJudicial = 69,
		BajaPorResolucionAdministrativa = 70,
		BajaPorUsoComun = 71,
		BajaPorIrregularidad = 72,
		ModificacionDeDatosDelInmueble = 73,
		ModificacionPorCorreccionDeMedidas = 74,
		ModificacionPorConstruccion = 75,
		ModificacionPorMejoraConstruccion = 76,
		ModificacionPorAfectacion = 77,
		ModificacionPorDesincorporacion = 78

	}
}
